//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matchup()
        {
            this.MatchupDetail = new HashSet<MatchupDetail>();
            this.MatchupLog = new HashSet<MatchupLog>();
            this.PlayerStatistics = new HashSet<PlayerStatistics>();
        }
    
        public int MatchupId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> MatchupTypeId { get; set; }
        public Nullable<int> Team_Away { get; set; }
        public Nullable<int> Team_Home { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public Nullable<int> Team_Away_Score { get; set; }
        public Nullable<int> Team_Home_Score { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
        public string CurrentQuarter { get; set; }
    
        public virtual MatchupType MatchupType { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchupDetail> MatchupDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchupLog> MatchupLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerStatistics> PlayerStatistics { get; set; }
    }
}
