//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public int Id { get; set; }
        public byte[] Img { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
